PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS aggregate_revision (singleton INTEGER PRIMARY KEY CHECK(singleton=1), revision INTEGER NOT NULL);
INSERT OR IGNORE INTO aggregate_revision VALUES (1,0);
CREATE TABLE IF NOT EXISTS profiles (id TEXT PRIMARY KEY, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE UNIQUE INDEX IF NOT EXISTS single_profile ON profiles ((1));
CREATE TABLE IF NOT EXISTS goals (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE UNIQUE INDEX IF NOT EXISTS active_goal ON goals ((json_extract(data,'$.status'))) WHERE json_extract(data,'$.status')='active';
CREATE TABLE IF NOT EXISTS plans (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, goal_id TEXT NOT NULL REFERENCES goals(id), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE UNIQUE INDEX IF NOT EXISTS accepted_plan ON plans ((json_extract(data,'$.status'))) WHERE json_extract(data,'$.status')='accepted';
CREATE TABLE IF NOT EXISTS plan_sessions (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, date TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS plan_memberships (plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE, session_id TEXT NOT NULL REFERENCES plan_sessions(id), PRIMARY KEY(plan_id,session_id));
CREATE TABLE IF NOT EXISTS workout_logs (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, session_id TEXT REFERENCES plan_sessions(id), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE UNIQUE INDEX IF NOT EXISTS manual_link ON workout_logs (session_id) WHERE session_id IS NOT NULL AND json_extract(data,'$.source')='manual';
CREATE TABLE IF NOT EXISTS daily_check_ins (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, date TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), UNIQUE(profile_id,date));
CREATE TABLE IF NOT EXISTS generation_jobs (id TEXT PRIMARY KEY, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency (key TEXT PRIMARY KEY, signature TEXT NOT NULL, response TEXT NOT NULL, status INTEGER NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS migrations (version INTEGER PRIMARY KEY);
INSERT OR IGNORE INTO migrations VALUES (1);
